/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTelegramUsersRouteImport } from './routes/_app.telegram-users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReturnsRouteImport } from './routes/_app.returns'
import { Route as AppReceiptTemplatesRouteImport } from './routes/_app.receipt-templates'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppMovementsRouteImport } from './routes/_app.movements'
import { Route as AppInventoriesRouteImport } from './routes/_app.inventories'
import { Route as AppInoutsRouteImport } from './routes/_app.inouts'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as PublicTemplatesTokenRouteImport } from './routes/public.templates.$token'
import { Route as AppPurchasesIdRouteImport } from './routes/_app.purchases_.$id'
import { Route as AppMovementsIdRouteImport } from './routes/_app.movements_.$id'
import { Route as AppInventoriesIdRouteImport } from './routes/_app.inventories_.$id'
import { Route as AppInoutsIdRouteImport } from './routes/_app.inouts_.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTelegramUsersRoute = AppTelegramUsersRouteImport.update({
  id: '/telegram-users',
  path: '/telegram-users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptTemplatesRoute = AppReceiptTemplatesRouteImport.update({
  id: '/receipt-templates',
  path: '/receipt-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoriesRoute = AppInventoriesRouteImport.update({
  id: '/inventories',
  path: '/inventories',
  getParentRoute: () => AppRoute,
} as any)
const AppInoutsRoute = AppInoutsRouteImport.update({
  id: '/inouts',
  path: '/inouts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const PublicTemplatesTokenRoute = PublicTemplatesTokenRouteImport.update({
  id: '/public/templates/$token',
  path: '/public/templates/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchasesIdRoute = AppPurchasesIdRouteImport.update({
  id: '/purchases_/$id',
  path: '/purchases/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIdRoute = AppMovementsIdRouteImport.update({
  id: '/movements_/$id',
  path: '/movements/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoriesIdRoute = AppInventoriesIdRouteImport.update({
  id: '/inventories_/$id',
  path: '/inventories/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInoutsIdRoute = AppInoutsIdRouteImport.update({
  id: '/inouts_/$id',
  path: '/inouts/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/inouts': typeof AppInoutsRoute
  '/inventories': typeof AppInventoriesRoute
  '/movements': typeof AppMovementsRoute
  '/payments': typeof AppPaymentsRoute
  '/purchases': typeof AppPurchasesRoute
  '/receipt-templates': typeof AppReceiptTemplatesRoute
  '/returns': typeof AppReturnsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/telegram-users': typeof AppTelegramUsersRoute
  '/users': typeof AppUsersRoute
  '/inouts/$id': typeof AppInoutsIdRoute
  '/inventories/$id': typeof AppInventoriesIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/public/templates/$token': typeof PublicTemplatesTokenRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AppDashboardRoute
  '/inouts': typeof AppInoutsRoute
  '/inventories': typeof AppInventoriesRoute
  '/movements': typeof AppMovementsRoute
  '/payments': typeof AppPaymentsRoute
  '/purchases': typeof AppPurchasesRoute
  '/receipt-templates': typeof AppReceiptTemplatesRoute
  '/returns': typeof AppReturnsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/telegram-users': typeof AppTelegramUsersRoute
  '/users': typeof AppUsersRoute
  '/': typeof AppIndexRoute
  '/inouts/$id': typeof AppInoutsIdRoute
  '/inventories/$id': typeof AppInventoriesIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/purchases/$id': typeof AppPurchasesIdRoute
  '/public/templates/$token': typeof PublicTemplatesTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inouts': typeof AppInoutsRoute
  '/_app/inventories': typeof AppInventoriesRoute
  '/_app/movements': typeof AppMovementsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/receipt-templates': typeof AppReceiptTemplatesRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/telegram-users': typeof AppTelegramUsersRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inouts_/$id': typeof AppInoutsIdRoute
  '/_app/inventories_/$id': typeof AppInventoriesIdRoute
  '/_app/movements_/$id': typeof AppMovementsIdRoute
  '/_app/purchases_/$id': typeof AppPurchasesIdRoute
  '/public/templates/$token': typeof PublicTemplatesTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/inouts'
    | '/inventories'
    | '/movements'
    | '/payments'
    | '/purchases'
    | '/receipt-templates'
    | '/returns'
    | '/sales'
    | '/settings'
    | '/telegram-users'
    | '/users'
    | '/inouts/$id'
    | '/inventories/$id'
    | '/movements/$id'
    | '/purchases/$id'
    | '/public/templates/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/inouts'
    | '/inventories'
    | '/movements'
    | '/payments'
    | '/purchases'
    | '/receipt-templates'
    | '/returns'
    | '/sales'
    | '/settings'
    | '/telegram-users'
    | '/users'
    | '/'
    | '/inouts/$id'
    | '/inventories/$id'
    | '/movements/$id'
    | '/purchases/$id'
    | '/public/templates/$token'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/dashboard'
    | '/_app/inouts'
    | '/_app/inventories'
    | '/_app/movements'
    | '/_app/payments'
    | '/_app/purchases'
    | '/_app/receipt-templates'
    | '/_app/returns'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/telegram-users'
    | '/_app/users'
    | '/_app/'
    | '/_app/inouts_/$id'
    | '/_app/inventories_/$id'
    | '/_app/movements_/$id'
    | '/_app/purchases_/$id'
    | '/public/templates/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PublicTemplatesTokenRoute: typeof PublicTemplatesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telegram-users': {
      id: '/_app/telegram-users'
      path: '/telegram-users'
      fullPath: '/telegram-users'
      preLoaderRoute: typeof AppTelegramUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipt-templates': {
      id: '/_app/receipt-templates'
      path: '/receipt-templates'
      fullPath: '/receipt-templates'
      preLoaderRoute: typeof AppReceiptTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements': {
      id: '/_app/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventories': {
      id: '/_app/inventories'
      path: '/inventories'
      fullPath: '/inventories'
      preLoaderRoute: typeof AppInventoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inouts': {
      id: '/_app/inouts'
      path: '/inouts'
      fullPath: '/inouts'
      preLoaderRoute: typeof AppInoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/templates/$token': {
      id: '/public/templates/$token'
      path: '/public/templates/$token'
      fullPath: '/public/templates/$token'
      preLoaderRoute: typeof PublicTemplatesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/purchases_/$id': {
      id: '/_app/purchases_/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof AppPurchasesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements_/$id': {
      id: '/_app/movements_/$id'
      path: '/movements/$id'
      fullPath: '/movements/$id'
      preLoaderRoute: typeof AppMovementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventories_/$id': {
      id: '/_app/inventories_/$id'
      path: '/inventories/$id'
      fullPath: '/inventories/$id'
      preLoaderRoute: typeof AppInventoriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inouts_/$id': {
      id: '/_app/inouts_/$id'
      path: '/inouts/$id'
      fullPath: '/inouts/$id'
      preLoaderRoute: typeof AppInoutsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInoutsRoute: typeof AppInoutsRoute
  AppInventoriesRoute: typeof AppInventoriesRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReceiptTemplatesRoute: typeof AppReceiptTemplatesRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTelegramUsersRoute: typeof AppTelegramUsersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInoutsIdRoute: typeof AppInoutsIdRoute
  AppInventoriesIdRoute: typeof AppInventoriesIdRoute
  AppMovementsIdRoute: typeof AppMovementsIdRoute
  AppPurchasesIdRoute: typeof AppPurchasesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInoutsRoute: AppInoutsRoute,
  AppInventoriesRoute: AppInventoriesRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReceiptTemplatesRoute: AppReceiptTemplatesRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTelegramUsersRoute: AppTelegramUsersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppInoutsIdRoute: AppInoutsIdRoute,
  AppInventoriesIdRoute: AppInventoriesIdRoute,
  AppMovementsIdRoute: AppMovementsIdRoute,
  AppPurchasesIdRoute: AppPurchasesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PublicTemplatesTokenRoute: PublicTemplatesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
